### ISSUE TITLE
有些問題想要請教

### ISSUE THREAD

**Issue by ghost** [seanchang015181/Python60bootcamp#2]
在台電那有看到你的提問，也因為你的提問及截圖讓我更了解opendnp3

目前已經可監聽且建立多個outstation及設定config

新手想請教幾個關於 開源opendnp3 的問題：

opendnp3中 outstation 接收/傳送是從哪幾支功能實現
opendnp3中 outstation 使用哪幾支功能配置欲傳送的點位內容
就如同你在台電的提問，或許只要將code截圖就可以幫助我了

任何幫助，我將感激不盡
非常期待你的回覆

**Comment by seanchang015181** [comment]
OpenDNP3內建的功能是無法達到台電要求的

接收….OpenDNP3只有interface要自己實作SOEHandler
傳送….Save被動觸發

**Comment by ghost** [comment]
感謝你的回覆

我目前建立起幾個outstation後，可以連得上測試工具，畫面顯示部分數值為0，不確定是否為demo發送的

> plantNo: 99-99-9999-99-9
Line Current PhaseA: 0
Line Current PhaseB: 0
Line Current PhaseC: 0
Line Current PhaseN: 0
Line/Bus Voltage PhaseA: 0
Line/Bus Voltage PhaseB: 
Line/Bus Voltage PhaseC: 
kW: 
kVar: 
PF: 
Frequency: 
Wh: 
變流器 PF 設定值: 
變流器 P 設定值: 
變流器 Q 設定值: 
變流器 Vpset 設定值: 

以及console中也會顯示溝通log，截部分資訊
<img width="992" alt="截圖 2022-01-04 下午12 15 09" src="https://user-images.githubusercontent.com/79190847/148008788-acbc5469-d8b8-46ab-8f1a-b37ac189c07a.png">
讓我認為是否已有基礎 接收解析及包裝傳送 功能，不知道這樣認知是否有誤

還有些許疑問：
1. 接收….實作SOEHandler - 這個我有看過，但看說明是指“處理”外站接收的數據，而我找不到接收的方法
2. 傳送...save被動觸發 - 是指outstation update後就會被動觸發嗎？？或是有什麼我沒注意到的
3. 配置點位 以及 點位內容 是哪幾支功能可以實現？？

目前了解OpenDNP3的功能或許只打包及解析dnp3，
台電要求的功能除了業務邏輯外，有發生其他dnp3規範功能中opendnp3無法達成的嗎？？

感謝你的分享
你的回覆對我幫助非常的多
非常期待你的回覆

**Comment by ghost** [comment]
SOEHandler 說明是處理外站接收的數據
有找到 CommandHandler 說明是處理來自主站的命令請求
而demo用SuccessCommandHandler.getInstance()來實作

**Comment by seanchang015181** [comment]
你找不到接收數據的方法是因為OpenDNP3沒有提供function給你呼叫使用或改寫

你必須要自己改寫OpenDNP3 !

**Comment by seanchang015181** [comment]
大概列一下你需要改寫的項目
1. Command Handler
2. SOE Handler
3. Connection Handler
4. Dead Band
你會發現OpenDNP3只是半成品很多東西沒做完

**Comment by ghost** [comment]
非常感謝你的回應

> Command Handler
SOE Handler
Connection Handler
Dead Band

應台電要求只需實作出外站功能的情況下，
好像只需要改寫CommandHandler、ConnectionHandler、DeadBand這三項，不知道理解對不對．

還有問題要請教
1. Analog Input、Output的部分，有看到以下相關類，但如何填入資料（回報的配置點位 以及 點位內容）不是很理解

>AnalogInput
AnalogOutputDouble64
AnalogOutputFloat32
AnalogOutputInt16
AnalogOutputInt32
AnalogOutputStatus

**Comment by ghost** [comment]
Hi @seanchang015181 :
    目前已掌握設置AnalogInput的點位及內容的方法，也理解到經由update後會更新outstation的AnalogInput內容，收到輪詢後會將已存內容發出。
然而有些許問題想請教：

- 目前僅會設置class0資料，想請問，因應台電輪詢要求，如何同時設置class0、1及2？
- 事件訊號中需要將32點位分別設置class1及2（例：class1(0-19)class2(20-30)）嗎？還是32點位全設置class1或class2？

還請指點。
